inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'

Bundler/OrderedGems:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Metrics/BlockLength:
  Max: 75
